name: Deploy Hugo via rsync over SSH

permissions:
  contents: read

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go (for Cache Hugo Modules)
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true 

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.148.2'
          extended: true

      - name: Cache Hugo modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/hugo_cache   # Hugo modules
            resources/_gen        # Processed assets
          key: hugo-${{ runner.os }}-${{ hashFiles('**/go.mod', '**/go.sum', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-hugo-
              
      - name: Setup Node (LTS) with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'           # or '18.x'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install Node.js dependencies
        run: |
          npm ci || (echo "npm ci failed, retrying..." && sleep 5 && npm ci)

      - name: Build Hugo
        run: |
          HUGO_ENV=production hugo --gc --minify --panicOnWarning
          test -s public/index.html

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts (pinned)
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SERVER_HOST_KEY }}" >> ~/.ssh/known_hosts
                  
      - name: Atomic deploy (rsync + symlink)
        run: |
          set -euo pipefail
          TS="$(date +%Y%m%d%H%M%S)"
          RELEASES="${{ secrets.DEPLOY_PATH }}/releases"
          TARGET="$RELEASES/$TS"

          ssh -p "${{ secrets.SERVER_PORT }}" "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" \
            "mkdir -p '$RELEASES'"

          rsync -az --delete --chmod=F644,D755 \
            -e "ssh -p ${{ secrets.SERVER_PORT }} -o PreferredAuthentications=publickey" \
            public/ "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:$TARGET"

          ssh -p "${{ secrets.SERVER_PORT }}" "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" \
            "ln -sfn '$TARGET' '${{ secrets.DEPLOY_PATH }}/current' && \
             find '$RELEASES' -maxdepth 1 -mindepth 1 -type d | sort -r | tail -n +6 | xargs -r rm -rf"
